database:
  host: localhost
  port: 5432
  user: telemetryai
  password: telemetryai
  dbname: telemetryai

app:
  host: 0.0.0.0
  port: 8080
  jwt_secret: your-secret-keyChangeInProduction
  nlp_service_url: http://nlp-service:5000

nats:
  urls: nats:4222
  topic: raw.logs
  error_topic: error