// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: internal/transport/grpc/apikeys.proto

package grpc

import (
	"context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const (
	APIKeyService_AddAPIKey_FullMethodName      = "/grpc.APIKeyService/AddAPIKey"
	APIKeyService_DeleteAPIKey_FullMethodName = "/grpc.APIKeyService/DeleteAPIKey"
	APIKeyService_ListAPIKeys_FullMethodName   = "/grpc.APIKeyService/ListAPIKeys"
)

type AddAPIKeyRequest struct {
	ApiKey    string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
}

func (x *AddAPIKeyRequest) Reset()                    { *x = AddAPIKeyRequest{} }
func (x *AddAPIKeyRequest) String() string        { return "" }
func (*AddAPIKeyRequest) ProtoMessage()       {}
func (*AddAPIKeyRequest) Descriptor() ([]byte, []int) { return nil, nil }
func (x *AddAPIKeyRequest) GetApiKey() string    { return x.ApiKey }
func (x *AddAPIKeyRequest) GetProjectId() string { return x.ProjectId }

type AddAPIKeyResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddAPIKeyResponse) Reset()                    { *x = AddAPIKeyResponse{} }
func (x *AddAPIKeyResponse) String() string        { return "" }
func (*AddAPIKeyResponse) ProtoMessage()           {}
func (*AddAPIKeyResponse) Descriptor() ([]byte, []int) { return nil, nil }
func (x *AddAPIKeyResponse) GetSuccess() bool    { return x.Success }
func (x *AddAPIKeyResponse) GetError() string    { return x.Error }

type DeleteAPIKeyRequest struct {
	ApiKey string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
}

func (x *DeleteAPIKeyRequest) Reset()                    { *x = DeleteAPIKeyRequest{} }
func (x *DeleteAPIKeyRequest) String() string        { return "" }
func (*DeleteAPIKeyRequest) ProtoMessage()           {}
func (*DeleteAPIKeyRequest) Descriptor() ([]byte, []int) { return nil, nil }
func (x *DeleteAPIKeyRequest) GetApiKey() string { return x.ApiKey }

type DeleteAPIKeyResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteAPIKeyResponse) Reset()                    { *x = DeleteAPIKeyResponse{} }
func (x *DeleteAPIKeyResponse) String() string        { return "" }
func (*DeleteAPIKeyResponse) ProtoMessage()           {}
func (*DeleteAPIKeyResponse) Descriptor() ([]byte, []int) { return nil, nil }
func (x *DeleteAPIKeyResponse) GetSuccess() bool { return x.Success }
func (x *DeleteAPIKeyResponse) GetError() string   { return x.Error }

type ListAPIKeysRequest struct {
	Filter string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *ListAPIKeysRequest) Reset()                    { *x = ListAPIKeysRequest{} }
func (x *ListAPIKeysRequest) String() string        { return "" }
func (*ListAPIKeysRequest) ProtoMessage()           {}
func (*ListAPIKeysRequest) Descriptor() ([]byte, []int) { return nil, nil }
func (x *ListAPIKeysRequest) GetFilter() string { return x.Filter }

type APIKeyPair struct {
	ApiKey    string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
}

func (x *APIKeyPair) Reset()                    { *x = APIKeyPair{} }
func (x *APIKeyPair) String() string        { return "" }
func (*APIKeyPair) ProtoMessage()           {}
func (*APIKeyPair) Descriptor() ([]byte, []int) { return nil, nil }
func (x *APIKeyPair) GetApiKey() string    { return x.ApiKey }
func (x *APIKeyPair) GetProjectId() string { return x.ProjectId }

type ListAPIKeysResponse struct {
	Keys []*APIKeyPair `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *ListAPIKeysResponse) Reset()                    { *x = ListAPIKeysResponse{} }
func (x *ListAPIKeysResponse) String() string        { return "" }
func (*ListAPIKeysResponse) ProtoMessage()           {}
func (*ListAPIKeysResponse) Descriptor() ([]byte, []int) { return nil, nil }
func (x *ListAPIKeysResponse) GetKeys() []*APIKeyPair { return x.Keys }

type APIKeyServiceClient interface {
	AddAPIKey(ctx context.Context, in *AddAPIKeyRequest, opts ...grpc.CallOption) (*AddAPIKeyResponse, error)
	DeleteAPIKey(ctx context.Context, in *DeleteAPIKeyRequest, opts ...grpc.CallOption) (*DeleteAPIKeyResponse, error)
	ListAPIKeys(ctx context.Context, in *ListAPIKeysRequest, opts ...grpc.CallOption) (*ListAPIKeysResponse, error)
}

type apiKeyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIKeyServiceClient(cc grpc.ClientConnInterface) APIKeyServiceClient {
	return &apiKeyServiceClient{cc}
}

func (c *apiKeyServiceClient) AddAPIKey(ctx context.Context, in *AddAPIKeyRequest, opts ...grpc.CallOption) (*AddAPIKeyResponse, error) {
	out := new(AddAPIKeyResponse)
	err := c.cc.Invoke(ctx, APIKeyService_AddAPIKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeyServiceClient) DeleteAPIKey(ctx context.Context, in *DeleteAPIKeyRequest, opts ...grpc.CallOption) (*DeleteAPIKeyResponse, error) {
	out := new(DeleteAPIKeyResponse)
	err := c.cc.Invoke(ctx, APIKeyService_DeleteAPIKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeyServiceClient) ListAPIKeys(ctx context.Context, in *ListAPIKeysRequest, opts ...grpc.CallOption) (*ListAPIKeysResponse, error) {
	out := new(ListAPIKeysResponse)
	err := c.cc.Invoke(ctx, APIKeyService_ListAPIKeys_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _APIKeyServiceClient = APIKeyServiceClient(nil)

type APIKeyServiceServer interface {
	AddAPIKey(context.Context, *AddAPIKeyRequest) (*AddAPIKeyResponse, error)
	DeleteAPIKey(context.Context, *DeleteAPIKeyRequest) (*DeleteAPIKeyResponse, error)
	ListAPIKeys(context.Context, *ListAPIKeysRequest) (*ListAPIKeysResponse, error)
}

type UnimplementedAPIKeyServiceServer struct{}

func (UnimplementedAPIKeyServiceServer) AddAPIKey(context.Context, *AddAPIKeyRequest) (*AddAPIKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAPIKey not implemented")
}

func (UnimplementedAPIKeyServiceServer) DeleteAPIKey(context.Context, *DeleteAPIKeyRequest) (*DeleteAPIKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAPIKey not implemented")
}

func (UnimplementedAPIKeyServiceServer) ListAPIKeys(context.Context, *ListAPIKeysRequest) (*ListAPIKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAPIKeys not implemented")
}

var _APIKeyServiceServer = APIKeyServiceServer(nil)

func RegisterAPIKeyServiceServer(s grpc.Server, srv APIKeyServiceServer) {
	s.RegisterService(&grpc.ServiceDesc{
		ServiceName: "grpc.APIKeyService",
		HandlerType: (*APIKeyServiceServer)(nil),
		Methods: []grpc.MethodDesc{
			{MethodName: "AddAPIKey", Handler: _APIKeyService_AddAPIKey_Handler},
			{MethodName: "DeleteAPIKey", Handler: _APIKeyService_DeleteAPIKey_Handler},
			{MethodName: "ListAPIKeys", Handler: _APIKeyService_ListAPIKeys_Handler},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "internal/transport/grpc/apikeys.proto",
	}, srv)
}

func _APIKeyService_AddAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeyServiceServer).AddAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: APIKeyService_AddAPIKey_FullMethodName}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeyServiceServer).AddAPIKey(ctx, req.(*AddAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeyService_DeleteAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeyServiceServer).DeleteAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: APIKeyService_DeleteAPIKey_FullMethodName}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeyServiceServer).DeleteAPIKey(ctx, req.(*DeleteAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeyService_ListAPIKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAPIKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeyServiceServer).ListAPIKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: APIKeyService_ListAPIKeys_FullMethodName}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeyServiceServer).ListAPIKeys(ctx, req.(*ListAPIKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}