version: "3.8"

services:
  api:
    image: alpine:latest
    container_name: api
    command: ["sh", "-c", "while true; do echo 'API: ERROR while proccesing request'; sleep 50; done"]

  worker:
    image: alpine:latest
    container_name: worker
    command: ["sh", "-c", "while true; do echo 'Worker: processing job'; sleep 3; done"]
