// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: internal/transport/grpc/apikeys.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAPIKeyRequest) Reset() {
	*x = AddAPIKeyRequest{}
	mi := &file_internal_transport_grpc_apikeys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAPIKeyRequest) ProtoMessage() {}

func (x *AddAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_apikeys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*AddAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_apikeys_proto_rawDescGZIP(), []int{0}
}

func (x *AddAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AddAPIKeyRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type AddAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAPIKeyResponse) Reset() {
	*x = AddAPIKeyResponse{}
	mi := &file_internal_transport_grpc_apikeys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAPIKeyResponse) ProtoMessage() {}

func (x *AddAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_apikeys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*AddAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_apikeys_proto_rawDescGZIP(), []int{1}
}

func (x *AddAPIKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddAPIKeyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAPIKeyRequest) Reset() {
	*x = DeleteAPIKeyRequest{}
	mi := &file_internal_transport_grpc_apikeys_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAPIKeyRequest) ProtoMessage() {}

func (x *DeleteAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_apikeys_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_apikeys_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type DeleteAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAPIKeyResponse) Reset() {
	*x = DeleteAPIKeyResponse{}
	mi := &file_internal_transport_grpc_apikeys_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAPIKeyResponse) ProtoMessage() {}

func (x *DeleteAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_apikeys_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_apikeys_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteAPIKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteAPIKeyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListAPIKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysRequest) Reset() {
	*x = ListAPIKeysRequest{}
	mi := &file_internal_transport_grpc_apikeys_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysRequest) ProtoMessage() {}

func (x *ListAPIKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_apikeys_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysRequest.ProtoReflect.Descriptor instead.
func (*ListAPIKeysRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_apikeys_proto_rawDescGZIP(), []int{4}
}

type APIKeyPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyPair) Reset() {
	*x = APIKeyPair{}
	mi := &file_internal_transport_grpc_apikeys_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyPair) ProtoMessage() {}

func (x *APIKeyPair) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_apikeys_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyPair.ProtoReflect.Descriptor instead.
func (*APIKeyPair) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_apikeys_proto_rawDescGZIP(), []int{5}
}

func (x *APIKeyPair) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *APIKeyPair) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListAPIKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*APIKeyPair          `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysResponse) Reset() {
	*x = ListAPIKeysResponse{}
	mi := &file_internal_transport_grpc_apikeys_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysResponse) ProtoMessage() {}

func (x *ListAPIKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_apikeys_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysResponse.ProtoReflect.Descriptor instead.
func (*ListAPIKeysResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_apikeys_proto_rawDescGZIP(), []int{6}
}

func (x *ListAPIKeysResponse) GetKeys() []*APIKeyPair {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_internal_transport_grpc_apikeys_proto protoreflect.FileDescriptor

const file_internal_transport_grpc_apikeys_proto_rawDesc = "" +
	"\n" +
	"%internal/transport/grpc/apikeys.proto\x12\x04grpc\"J\n" +
	"\x10AddAPIKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"C\n" +
	"\x11AddAPIKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\".\n" +
	"\x13DeleteAPIKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"F\n" +
	"\x14DeleteAPIKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x14\n" +
	"\x12ListAPIKeysRequest\"D\n" +
	"\n" +
	"APIKeyPair\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\";\n" +
	"\x13ListAPIKeysResponse\x12$\n" +
	"\x04keys\x18\x01 \x03(\v2\x10.grpc.APIKeyPairR\x04keys2\xd8\x01\n" +
	"\rAPIKeyService\x12<\n" +
	"\tAddAPIKey\x12\x16.grpc.AddAPIKeyRequest\x1a\x17.grpc.AddAPIKeyResponse\x12E\n" +
	"\fDeleteAPIKey\x12\x19.grpc.DeleteAPIKeyRequest\x1a\x1a.grpc.DeleteAPIKeyResponse\x12B\n" +
	"\vListAPIKeys\x12\x18.grpc.ListAPIKeysRequest\x1a\x19.grpc.ListAPIKeysResponseB+Z)telemetry-service/internal/transport/grpcb\x06proto3"

var (
	file_internal_transport_grpc_apikeys_proto_rawDescOnce sync.Once
	file_internal_transport_grpc_apikeys_proto_rawDescData []byte
)

func file_internal_transport_grpc_apikeys_proto_rawDescGZIP() []byte {
	file_internal_transport_grpc_apikeys_proto_rawDescOnce.Do(func() {
		file_internal_transport_grpc_apikeys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_apikeys_proto_rawDesc), len(file_internal_transport_grpc_apikeys_proto_rawDesc)))
	})
	return file_internal_transport_grpc_apikeys_proto_rawDescData
}

var file_internal_transport_grpc_apikeys_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_transport_grpc_apikeys_proto_goTypes = []any{
	(*AddAPIKeyRequest)(nil),     // 0: grpc.AddAPIKeyRequest
	(*AddAPIKeyResponse)(nil),    // 1: grpc.AddAPIKeyResponse
	(*DeleteAPIKeyRequest)(nil),  // 2: grpc.DeleteAPIKeyRequest
	(*DeleteAPIKeyResponse)(nil), // 3: grpc.DeleteAPIKeyResponse
	(*ListAPIKeysRequest)(nil),   // 4: grpc.ListAPIKeysRequest
	(*APIKeyPair)(nil),           // 5: grpc.APIKeyPair
	(*ListAPIKeysResponse)(nil),  // 6: grpc.ListAPIKeysResponse
}
var file_internal_transport_grpc_apikeys_proto_depIdxs = []int32{
	5, // 0: grpc.ListAPIKeysResponse.keys:type_name -> grpc.APIKeyPair
	0, // 1: grpc.APIKeyService.AddAPIKey:input_type -> grpc.AddAPIKeyRequest
	2, // 2: grpc.APIKeyService.DeleteAPIKey:input_type -> grpc.DeleteAPIKeyRequest
	4, // 3: grpc.APIKeyService.ListAPIKeys:input_type -> grpc.ListAPIKeysRequest
	1, // 4: grpc.APIKeyService.AddAPIKey:output_type -> grpc.AddAPIKeyResponse
	3, // 5: grpc.APIKeyService.DeleteAPIKey:output_type -> grpc.DeleteAPIKeyResponse
	6, // 6: grpc.APIKeyService.ListAPIKeys:output_type -> grpc.ListAPIKeysResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_transport_grpc_apikeys_proto_init() }
func file_internal_transport_grpc_apikeys_proto_init() {
	if File_internal_transport_grpc_apikeys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_apikeys_proto_rawDesc), len(file_internal_transport_grpc_apikeys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_grpc_apikeys_proto_goTypes,
		DependencyIndexes: file_internal_transport_grpc_apikeys_proto_depIdxs,
		MessageInfos:      file_internal_transport_grpc_apikeys_proto_msgTypes,
	}.Build()
	File_internal_transport_grpc_apikeys_proto = out.File
	file_internal_transport_grpc_apikeys_proto_goTypes = nil
	file_internal_transport_grpc_apikeys_proto_depIdxs = nil
}
